spring:
  datasource:
    url: jdbc:mysql://localhost:3307/saegil  # 데이터베이스 URL 설정
    #    url: jdbc:mysql://mysql:3306/saegil  # Docker Compose 서비스명 'mysql'로 연결

    username: root
    password: 1868
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # schema.sql을 사용할 경우 none으로 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL 포맷 정리
        use_sql_comments: true  # SQL 쿼리에 주석 추가
        generate_statistics: true  # Hibernate 통계 정보 활성화
      logging:
        level:
          org.hibernate.SQL: debug  # Hibernate SQL 로그 활성화
          org.hibernate.type.descriptor.sql: trace  # SQL 변수 값 추적
  sql:
    init:
      mode: always  # schema.sql 파일을 항상 실행하도록 설정
  mvc:
    web:
      resources:
        add-mappings: false

server:
  port: 8081

